apiVersion: v1
kind: ConfigMap
metadata:
  name: angular-nginx-config
data:
  default.conf: |
    server {
      listen 80;

      root /usr/share/nginx/html;
      index index.html;

      location / {
        try_files $uri $uri/ /index.html;
      }

      # error_page 404 /index.html;
    }
