apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: meea-match-maker-production
  labels:
    app: match-maker
    type: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: match-maker
      type: backend
  template:
    metadata:
      labels:
        app: match-maker
        type: backend
    spec:
      containers:
        - image: ghcr.io/pm4fs25match-maker/match-maker-backend:v0.0.1
          imagePullPolicy: Always
          name: backend
          env:
            - name: FRONTEND_BASEURL
              value: https://mm.pm4.init-lab.ch
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          ports:
            - name: http
              containerPort: 8080
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          volumeMounts:
            - mountPath: /data
              name: h2-storage
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      volumes:
        - name: h2-storage
          persistentVolumeClaim:
            claimName: h2-database
